name: Build and Deploy Go App

on:
  push:
    branches:
      - http_test_assigment_4

jobs:
  build:
    name: nitin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assignment_4_task_http/hello

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build Go Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main
      - name: Check Linters for run
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6
          working-directory: assignment_4_task_http/hello